function submitExam() {
    const answerSection = document.getElementById('answer');
    answerSection.style.display = 'block';
    const correctAnswers = {
        "question1": "C",
        "question2": "D",
        "question3": "A",
        "question4": "A",
        "question5": "A",
        "question6": "A",
        "question7": "A",
        "question8": "D",
        "question9": "C",
        "question10": "A",
        "question11": "C",
        "question12": "A",
        "question13": "D",
        "question14": "A",
        "question15": "C",
        "question16": "C",
        "question17": "C",
        "question18": "C",
        "question19": "B",
        "question20": "C",
        "question21": "B",
        "question22": "D",
        "question23": "B",
        "question24": "B",
        "question25": "D",
        "question26": "B",
        "question27": "B",
        "question28": "A",
        "question29": "C",
        "question30": "A",
        "question31": "A",
        "question32": "B",
        "question33": "A",
        "question34": "B",
        "question35": "D",
        "question36": "D",
        "question37": "D",
        "question38": "B",
        "question39": "B",
        "question40": "D",
        "question41": "D",
        "question42": "C",
        "question43": "B",
        "question44": "C",
        "question45": "B",
        "question46": "C",
        "question47": "B",
        "question48": "D",
        "question49": "D",
        "question50": "D",
        "question51": "C",
        "question52": "B",
        "question53": "A",
        "question54": "B",
        "question55": "C",
        "question56": "B",
        "question57": "C",
        "question58": "B",
        "question59": "C",
        "question60": "C",
        "question61": "B",
        "question62": "D",
        "question63": "A",
        "question64": "D",
        "question65": "B",
        "question66": "A",
        "question67": "D",
        "question68": "D",
        "question69": "B",
        "question70": "D",
        "question71": "B",
        "question72": "B",
        "question73": "D",
        "question74": "B",
        "question75": "A",
        "question76": "A",
        "question77": "B",
        "question78": "B",
        "question79": "D",
        "question80": "A",
        "question81": "D",
        "question82": "D",
        "question83": "C",
        "question84": "D",
        "question85": "C",
        "question86": "A",
        "question87": "D",
        "question88": "D",
        "question89": "A",
        "question90": "A",
        "question91": "C",
        "question92": "C",
        "question93": "B",
        "question94": "B",
        "question95": "A",
        "question96": "C",
        "question97": "D",
        "question98": "B",
        "question99": "A",
        "question100": "B",
    };
    let score = 0;
    let totalQuestions = Object.keys(correctAnswers).length;

    // Check user responses
    for (let question in correctAnswers) {
        const selected = document.querySelector(`input[name=${question}]:checked`);
        if (selected && selected.value === correctAnswers[question]) {
            score++;
        }
    }

    // Display score
    const scoreDisplay = document.getElementById('score');
    scoreDisplay.innerHTML = `Your Score: ${score} / ${totalQuestions}`;
    alert(`Your answers have been submitted! You scored ${score} out of ${totalQuestions}.`);
}