function submitExam() {
    const answerSection = document.getElementById('answer');
    answerSection.style.display = 'block';
    const correctAnswers = {
        "question1": "C",
        "question2": "B",
        "question3": "C",
        "question4": "C",
        "question5": "C",
        "question6": "C",
        "question7": "C",
        "question8": "B",
        "question9": "B",
        "question10": "B",
        "question11": "C",
        "question12": "B",
        "question13": "C",
        "question14": "A",
        "question15": "B",
        "question16": "D",
        "question17": "B",
        "question18": "B",
        "question19": "B",
        "question20": "B",
        "question21": "B",
        "question22": "D",
        "question23": "D",
        "question24": "B",
        "question25": "D",
        "question26": "C",
        "question27": "B",
        "question28": "A",
        "question29": "A",
        "question30": "B",
        "question31": "D",
        "question32": "A",
        "question33": "C",
        "question34": "B",
        "question35": "D",
        "question36": "B",
        "question37": "A",
        "question38": "B",
        "question39": "B",
        "question40": "D",
        "question41": "C",
        "question42": "B",
        "question43": "C",
        "question44": "D",
        "question45": "D",
        "question46": "A",
        "question47": "C",
        "question48": "A",
        "question49": "B",
        "question50": "C",
        "question51": "D",
        "question52": "D",
        "question53": "B",
        "question54": "B",
        "question55": "D",
        "question56": "A",
        "question57": "C",
        "question58": "A",
        "question59": "C",
        "question60": "A",
        "question61": "A",
        "question62": "D",
        "question63": "C",
        "question64": "B",
        "question65": "C",
        "question66": "D",
        "question67": "C",
        "question68": "B",
        "question69": "C",
        "question70": "A",
        "question71": "C",
        "question72": "D",
        "question73": "D",
        "question74": "C",
        "question75": "A",
        "question76": "B",
        "question77": "D",
        "question78": "D",
        "question79": "B",
        "question80": "B",
        "question81": "D",
        "question82": "A",
        "question83": "A",
        "question84": "C",
        "question85": "B",
        "question86": "C",
        "question87": "B",
        "question88": "A",
        "question89": "B",
        "question90": "B",
        "question91": "D",
        "question92": "B",
        "question93": "D",
        "question94": "A",
        "question95": "C",
        "question96": "C",
        "question97": "B",
        "question98": "D",
        "question99": "D",
        "question100": "B",
        "question101": "B",
        "question102": "B",
        "question103": "C",
        "question104": "D",
        "question105": "A",
        "question106": "C",
        "question107": "A",
        "question108": "A",
        "question109": "C",
        "question110": "A"
    };
    let score = 0;
    let totalQuestions = Object.keys(correctAnswers).length;

    // Check user responses
    for (let question in correctAnswers) {
        const selected = document.querySelector(`input[name=${question}]:checked`);
        if (selected && selected.value === correctAnswers[question]) {
            score++;
        }
    }

    // Display score
    const scoreDisplay = document.getElementById('score');
    scoreDisplay.innerHTML = `Your Score: ${score} / ${totalQuestions}`;
    alert(`Your answers have been submitted! You scored ${score} out of ${totalQuestions}.`);
}